CREATE TABLE BLOCK (
  ID               BIGINT PRIMARY KEY AUTO_INCREMENT,
  START_NUMBER     LONG (200) NOT NULL,
  PALINDROME_COUNT LONG (200) NOT NULL,
  FIRST_PALINDROME VARCHAR (255) NOT NULL,
  LAST_PALINDROME  VARCHAR (255) NOT NULL
);